### ISSUE TITLE
Add animation to mdl-dialogs

### ISSUE THREAD

**Issue by mseemann** [mseemann/angular2-mdl#118]

**Comment by andreialecu** [comment]
I haven't tested yet, but it would be nice if you could pass an `$event` to the modal open function so that the animation appears to pop-up from the button/link it is triggered by.

This would be pretty nice for a certain app I'm working on, as there are a lot of clickable items and the visual feedback would be nice.

**Comment by mseemann** [comment]
please open an issue that coves this problem. i think there is a lot to talk about. for example: how to pass custom animations to the dialog. right now the animation is done with the angular2 dsl for animations and i have no idea how i could allow others to pass their own animation... thx!
