### ISSUE TITLE
z-index problem with menu

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#124]
When in my ([angular2-data-table 0.8.0](https://github.com/swimlane/angular2-data-table)) I use menu of angular2-mdl but z-index position is buggy and a scrollbar horizontal is scrolling because a width is added, I can't resolve it even with increment z-index of your component. When I use menu from material2 I do not have problem with z-index and scroll...

with this gif you can check the result when I don't use menu I don't have this scroll-horizontal ... 
![menu-angular2-mdl](https://cloud.githubusercontent.com/assets/2789203/19028428/17fd9430-893c-11e6-8d95-1f5d3e22a986.gif)

**Comment by mseemann** [comment]
i guess you are running in this problem: http://css-discuss.incutio.com/wiki/Overlapping_And_ZIndex

please provide a complete working example. otherwise it is impossible to check if there are any problems.

**Comment by istiti** [comment]
@mseemann ok, here you are: http://plnkr.co/edit/udDDyqinLONySQwmkE93?p=preview

I use your mdl-list here instead md-list of material2, but same error... you will see z-index problem and this scrollbar is added on horizontal

**Comment by mseemann** [comment]
there are a lot of html-elements that use position and creating there own z-Index context. that's why the z-index for the menu can not overlap the data-table. as said: http://css-discuss.incutio.com/wiki/Overlapping_And_ZIndex.

the vertical scrollbar seems to be a result of the dynamic width calculation of the data table. mdl-list and mdl-list-item are block elements that are designed by getmdl to get the maximum possible width. because the width is wider than it has to be you see a scrollbar.

sorry but i can't see any problems related to angular2-mdl.

**Comment by istiti** [comment]
@mseemann ok thanks for reactivity you check very fast issues :+1:  I just wonder why when using material2 menu component there isn't overlap  but I wil check each div and fix that, thanks still

**Comment by tonefolder** [comment]
I'm having the same issue (using `mdl-menu` inside of `mdl-list-item`).  I am able to fix the scroll bar issue by: 

1.  Wrapping the `button ` and `mdl-menu` in a `div ` element with `absolute` positioning applied.  
See  [this thread](https://github.com/google/material-design-lite/issues/948).
2.  Apply `relative` positioning to the `li` elements in the mdl-list.

Now the horizontal scroll bar is not an issue, but the menu itself is being overlapped to the point of being invisible.  I am going to check out the article posted above.  If I can figure out the overlapping issue, I will post some code here.
