### ISSUE TITLE
Dialog testabiliy

### ISSUE THREAD

**Issue by tb** [mseemann/angular2-mdl#130]
The inject of Angular2MdlAppComponent (see [here](https://github.com/mseemann/angular2-mdl/blob/angular2-mdl-1.x/src/app/dialog/dialog.component.ts#L40)) makes me wonder how I should structure tests now. I would like to avoid injecting Angular2MdlAppComponent because then I have to inject its dependencies (like i.e. AuthService).

Angular2MdlAppComponent should probably be mocked. Can you provide some example how this should be approached?

**Comment by mseemann** [comment]
Angular2MdlAppComponent is only used in the demo app to setDefaultViewContainerRef. this is the viewcontainerref the dialog is attached to. you can use every ViewContainerRef. for example the viewcontainerref from your testcomponent.

Background: i have used the ViewContainerRef from Angular2MdlAppComponent because this is the top most component and makes sure that the dialog really overlaps all other content with a z-index. if you look at the dom you'll see that the dialog-element is a sibling of the app-root-element.

**Comment by mseemann** [comment]
have a look at mdl-dialog.service.spec: "should be possible to open a custom dialog"
