### ISSUE TITLE
Tooltip positioning is not reliable

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl#224]
When tooltips are initiated out of view, they are being positioned incorrectly. As can be seen here http://plnkr.co/edit/0VAxWWq25kEGKchB0I3b?p=preview

EDIT:
 In the given plnkr it can be fixed by moving tooltip outside of the div, which is not an option if your div is an angular component.

**Comment by mseemann** [comment]
The problem is that you are using css transformations. See here what the specification says: https://www.w3.org/TR/css-transforms-1/#transform-rendering:

> Transformations do affect the visual layout on the canvas, but have no affect on the CSS layout itself. This also means transforms do not affect results of the Element Interface Extensions getClientRects() and getBoundingClientRect(),...

Material Design Lite works with getBoundingClientRect to calculate the position so it goes wrong if the tooltip is inside an element that was transformed.

There are at least two possible solutions for your case. First you can set the transform to none if the animation is done:
   
```
 .modal-example.animate {
      transform: none;
    }
```

Second move the tooltip out if the transformed element:

         <div class="modal-example" [class.animate]="showModal">
            <span [mdl-tooltip]="tt">Hover for tooltip</span>
          </div>
          
          <mdl-tooltip #tt="mdlTooltip">
              I should be relative
          </mdl-tooltip>

here is your plnkr with this approach: http://plnkr.co/edit/RhpFBhx5ch5Q7pgnE5R2?p=preview

There are other hacks to achieve the right position - but they are not browser agnostic - afaik.

**Comment by nikoTM** [comment]
Setting transform to none solves my issue. Thanks for the link to transform rendering.
