### ISSUE TITLE
Toggle tooltip position

### ISSUE THREAD

**Issue by Stoope** [mseemann/angular2-mdl#237]
When I click "TOGGLE TOOLTIP" at the end of the page http://mseemann.io/angular2-mdl/tooltip and then scroll page tooltip position doesn't match element position anymore

**Comment by mseemann** [comment]
need to think about how to achieve this without breaking the way the tooltip works in the regular cases. the tooltip is position fixed by the mdl css and usually will be hidden if a scroll starts. for your use case the tooltip needs to be positioned absolute and the calculations of the position needs to be different...

**Comment by Stoope** [comment]
Yes, it will be hard to achieve this behavior whith mdl library. May be it isn't right usercase for tooltip...

**Comment by mseemann** [comment]
Until now I didn't find a suitable way. Back to your usecase: have you tried styling the error-message in a way that it looks like a tooltip?

**Comment by Stoope** [comment]
No I back to way using static text for displaying errors. I used tooltip way in previous project when with bootstrap

**Comment by mseemann** [comment]
ok. then let's close this for now. I'll keep the possibility to open the tooltip programatically in code but remove it from the documentation. In case one came up with an idea how to solve this we can work again on it...
