### ISSUE TITLE
misaligned icons when placed inside mdl-menu-item

### ISSUE THREAD

**Issue by henyojess** [mseemann/angular2-mdl#255]
```
<mdl-menu #m1="mdlMenu" mdl-menu-position="bottom-right">
    <mdl-menu-item>
      <mdl-icon>settings</mdl-icon>
      <span>Settings</span>
    </mdl-menu-item>
    <mdl-menu-item>      
      <mdl-icon>exit_to_app</mdl-icon>
      <span>Sign out</span>      
    </mdl-menu-item>    
  </mdl-menu>
```

![screen shot 2016-11-25 at 10 15 23 pm](https://cloud.githubusercontent.com/assets/217474/20630193/84384232-b36a-11e6-8a12-728ca162f63f.png)

Would be nice if the icons are vertically aligned with the text on a mdl-menu-item element

**Comment by mseemann** [comment]
i can't fix this without changes to the original mdl css. please set the following style for the mdl-menu-item:
display: flex;
 align-items: center;

**Comment by henyojess** [comment]
how about setting the necessary style in src/lib/components/menu/mdl-menu-item.component.ts? 

```
mdl-menu-item > mdl-icon {
    vertical-align: middle;
}
```

**Comment by mseemann** [comment]
the problem is if i start fixing the mdl css it will be an endless nightmare. if they publish a new version it is right now only copying the scss src from mdl in this project. if i start changing anything i have to check that all styles are still working. This is something I don't have the capacities for. It's hard enough to stay up to date with angular. You can easily add this css style in your project...
