### ISSUE TITLE
Number type textfield updates model incorrectly

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl#275]
As can be seen [here](http://plnkr.co/edit/pDX1VW4ZTkXD0pHiOfAH?p=preview), when setting a new value on type="number" textfield, type of the model changes from number to string.

**Comment by mseemann** [comment]
will be fixed in the next release.

notes how to fix: because the original input is wrapped by a ControlValueAccessor that is not a NumberValueAccessor the value is not converted back to the type required by the type attribute. In `set value` the passed in value needs to be converted to a number (`parseFloat`) if the type is number.

**Comment by mseemann** [comment]
published in 2.6.0
