### ISSUE TITLE
mdl-table-selectable

### ISSUE THREAD

**Issue by sam-exile** [mseemann/angular2-mdl#28]
Hi, when i'm using mdl-table-selectable it gives

EXCEPTION: Error in http://localhost:4200/vendor/angular2-mdl/dist/components/table/mdl-table.component.js class MdlSelectableTableComponent - inline template:5:42

browser_adapter.ts:82 ORIGINAL EXCEPTION: No value accessor for ''

any idea?

**Comment by mseemann** [comment]
Hi, can you provide me some information how you are using the component - html code and javascript code? Are you using angular 2 RC4? Thx.

**Comment by sam-exile** [comment]
I have tried with the code from **table.component.ts**
https://github.com/mseemann/angular2-mdl/blob/master/src/app/tables/table.component.ts

yes I'm using angular 2 RC4

I have edited the inline template from (mdl-table.component.js) removed checkbox stuff but kept the mdl-checkbox, without the [ngModel] and the (ngModelChange). then it displays the checkbox and the table right.

That's what i could find so far.

gist here
https://gist.github.com/sam-exile/6c905131c9025bf68ec0e0cccc150ff8

Thanks.

**Comment by mseemann** [comment]
Thx for your additional information! You are right. The error is related to the mdl-checkbox. If i remove this component from the directives array of the mdl-table component i get the same error, because angular can now not evaluate the [ngModel] directive correctly (there is no ControlValueAccessor component at the same element). But i have no idea why in your case the mdl-checkbox component should not implement this interface. In fact the mdl-checkbox component does.

What kind of build system are you using? systemjs, webpack or something completely different? What kind of shim are you using for the reflection mechanism: reflect-metadata? core-js? 
Thanks.

**Comment by sam-exile** [comment]
Hi current configuration as follows...

- angular-cli: 1.0.0-beta.10
- systemjs@0.19.31
- systemjs-builder@0.15.20
- "es6-shim": "0.35.1",

Thanks.

**Comment by mseemann** [comment]
i have created a minimal test project:
 github: https://github.com/mseemann/a2-mdl-test
 running example: http://mseemann.github.io/a2-mdl-test
Do you see any difference to your project?

**Comment by sam-exile** [comment]
Hi,

I tried your test project, it works fine, however problem comes when i enable new forms "@angular/forms": "0.2.0",

to enable it from the main.ts i added,
disableDeprecatedForms() and  provideForms()

Thanks.

**Comment by mseemann** [comment]
Thank you very much for your help. You are right! The problem is the old form api. Unfortunately this is not a quick fix. I need to change from @angular/common to @angualr/forms. The easy part. The problem is that everybody who uses this package must also switch to the new forms api and configure this at the app bootstrap ( disableDeprecatedForms() and provideForms() ).

With rc5 the new forms api seems to be the default way. So my plan is to switch to the new forms api  if i upgrade this package to match the angular  rc5 release (https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub).

**Comment by sam-exile** [comment]
Okay thanks for the update, I appreciate your great work.
hope to see the change with the RC5, cheers!

**Comment by mseemann** [comment]
found a way to support both versions of the forms API - just released version 1.2.0 with this feature...
