### ISSUE TITLE
Plans / intentions of angular2-mdl

### ISSUE THREAD

**Issue by maku** [mseemann/angular2-mdl#30]
The first impression of angular2-mdl is really good and it looks "professional".

But I am curious what the intention of angular2-mdl is...
e.g.

- Is the library used in production applications? 
- Do you plan to support it for a longer time (e.g. support for an upcoming mdl 2.x)?
- Do you want to involve contributors?
- Or is it rather a proof of concept?

TIA

**Comment by mseemann** [comment]
1) Is the library used in production applications?
I don't know. But i use this library for my own projects because I didn't find an easy to use material design component library for angular 2 that is not in pre alpha state.
2) Do you plan to support it for a longer time (e.g. support for an upcoming mdl 2.x)?
It depends on what will mdl2 bring to us and when it will be ready to use. Also if angular 2 material (https://github.com/angular/material2) is ready may be it makes no sense to make a further development of this lib.
3) Do you want to involve contributors?
Everbody is welcome who want's to participate!
4) Or is it rather a proof of concept?
No. In this case only some components would be sufficient... But I wanted a complete lib that provides components that mdl provides.

**Comment by maku** [comment]
Thank you
