### ISSUE TITLE
Date picker and dropdown

### ISSUE THREAD

**Issue by ananda121** [mseemann/angular2-mdl#32]
Hi,

I did not find any date-picker and drop-down in angular2-mdl.

Can anybody suggest where can I get these 2 component with Angular2 and material design.

Thanks
Ananda

**Comment by mseemann** [comment]
Hi,

this is just an angular 2 wrapper for https://getmdl.io/components/index.html. Because there is no date-picker or a drop down, here is no one too.

Maybe you'll find what you are looking for at material2 (https://github.com/angular/material2)  or at  ng2-bootstrap (https://valor-software.com/ng2-bootstrap/#/)

michael
