### ISSUE TITLE
Provide an event if mdl-layout-drawer is hidden/shown on small devices

### ISSUE THREAD

**Issue by matthiasscudlik** [mseemann/angular2-mdl#331]
I want to use a mdl-layout with a fixed header and a fixed-drawer for desktop and small devices.
As i have a custom header i cannot use the automatically shown layout drawer button because it has an absolute position which doesn't fit. So i need an event to be able to know when to show/hide my custom button. When the drawer should be hidden or shown is handled in onQueryChange, but unfortunately there are no events fired (see here)[https://github.com/mseemann/angular2-mdl/blob/master/src/lib/components/layout/mdl-layout.component.ts#L198].
open/close are not fired and i'm not sure if they should, because it is semantically different.

Thanks a lot for your great work and best regards,
Matthias

**Comment by mseemann** [comment]
hi. your use case is quite special. did you check using the property isSmallScreen form the layout for your special needs? 

This would work in this way:

 @ViewChild('mdlLayout1') private mdlLayout1;

  public ngDoCheck() {
    console.log(this.mdlLayout1.isSmallScreen);
  }

Even so instead of making these changes to MdlLayoutComponent I'd rather go the way creating a special service that fires screensize events.

**Comment by matthiasscudlik** [comment]
Hi Michael,

your solution worked, though i'd prefer to have a "real" API / Event for that rather than using internal attributes.

Thanks a lot! :)

Best regards,
Matthias

**Comment by mseemann** [comment]
will work as follow:

```
  constructor(mdlScreenSizeService: MdlScreenSizeService) {

    mdlScreenSizeService.sizes().subscribe( (isSmall) => {
      console.log(`is ${isSmall? 'small' : 'large'} screen`);
    });

  }
```
