### ISSUE TITLE
some question for mdl-icon

### ISSUE THREAD

**Issue by xpyanchong** [mseemann/angular2-mdl#38]
Hi,The project is very awesome.
When i use button,look like they have a diffrerent for getmdl;
When repeatedly the button,angular2-mdl will select that icon,but getmdl is not;
angular2-mdl will show a blue selected area,like text seleted.

If change 

> mdl-button to button

the show style is same.So i think this is a style issue.
Demo url with `http://mseemann.de/angular2-mdl/button`
                        `https://getmdl.io/components/index.html#buttons-section`

**Comment by mseemann** [comment]
Hi,

what do you mean by "When repeatedly the button,angular2-mdl will select that icon,but getmdl is not;"?

Can you provide a screenshot?

**Comment by xpyanchong** [comment]
![before](https://cloud.githubusercontent.com/assets/18358979/17950889/b2357cf4-6a90-11e6-8d17-4691028e5e93.png)

Look like icon can select

**Comment by mseemann** [comment]
Ah! I see! Thx for your help.
 The problem is that mdl-button is not a real html button. To get the same behavior i need to add the possibility to use the mdl-button as a directive and not as a component. So instead of:

`<mdl-button>x</mdl-button>`

there must be the possibility to use mdl-button on a button:

`<button mdl-button>x</button>`

I'll fix this asap.

**Comment by mseemann** [comment]
fixed: npm version 1.4.3
