### ISSUE TITLE
Pattern on Text Input invalidating Reactive Forms 

### ISSUE THREAD

**Issue by pauljlucas** [mseemann/angular2-mdl#49]
I am seeing that if I use reactive forms and build a FormGroup with validators on fields it works fine on its own. Then when i add pattern and error-msg to a textField (that matches the FormGroup validators), the FormGroup is ALWAYS invalid. Any ideas on this?

Even if i dont have a pattern validator on the FormGroup it still happens.

Side note, the URL in the readme isnt updated to http://mseemann.io/angular2-mdl/ yet :)

**Comment by mseemann** [comment]
thx. the easy part:

> the URL in the readme isnt updated to

should be fixed now. 👍 

the pattern problem needs some more investigation. the problem seems to be that i have used the native validity state like mdl does. may be this was a mistake...

**Comment by mseemann** [comment]
I have added to examples here: http://mseemann.io/angular2-mdl/reactiveForms

The first email field uses FormControl, pattern and error-mg. Seems to work. But it must be ensured that the FormControl validator and the pattern calculating the same validity state. Otherwise they are fighting against each other :( The validator is the angular code and the pattern is the browsers native code.

The second email field avoids using the pattern attribute and sets the right css class if the form is invalid: [class.is-invalid]="email2.invalid". But now the Browser didn't know that we have our own validity checking. To disable this i have added the attribute disableNativeValidityChecking to avoid this. It seems to work. But I'm not sure if this is a proper solution. What do you think?

**Comment by pauljlucas** [comment]
Since you are using Form control on the first one that makes sense to me, everything seems to work fine that way. But my assumption is most people will lean towards Reactive because they have much more flexibility. 

What if you do this: only If the field has formControlName on it then add that disableNativeValidityChecking and enable the css check and use the error-msg to populate the error? That seems like a good compromise for the library and enables flexibility in use and only disables native checking if absolutely needed.

Otherwise i dont know much about the other consequences of using disableNativeValidityChecking :) but it seems like this works well. I can implement it when you add it and give you some feedback on how it is working.

**Comment by mseemann** [comment]
thx for your feedback. I have included this feature in package 1.4.5. Let me know if it works for you. Here is a more detailed description: https://github.com/mseemann/angular2-mdl/wiki/Mdl-Textfield-and-native-validity-checking.
