### ISSUE TITLE
tabs not scroll

### ISSUE THREAD

**Issue by istiti** [mseemann/angular2-mdl#56]
I have tabs with 6 tab when I resize my tabs are cutted, there is no scroll vertical, and icons aren't alined vetically

how fix ?

**Comment by istiti** [comment]
ok is there plunk ?

**Comment by istiti** [comment]
If you want you can check this gif 
!
[angular2-mdl](https://cloud.githubusercontent.com/assets/2789203/18158316/df4b154a-7022-11e6-85ed-5950b926cc25.gif)

**Comment by mseemann** [comment]
Please checkout this thread https://github.com/google/material-design-lite/issues/1380. Seems this is not supported by material design lite.so it is not supported by this lib too:(

**Comment by mseemann** [comment]
May be this threat is also helpful: http://stackoverflow.com/questions/31304232/how-can-i-make-header-scrollable-for-smaller-screens-in-mdl

**Comment by asnapper** [comment]
IMO this issue should be re-opened as it seems to be possible with stock mdl, see this example:
http://codepen.io/surma/pen/RPOREb

**Comment by leonelngande** [comment]
Is there a fix for this? Because am facing the same issue. And as @asnapper mentioned above the codepen example shows the feature is supported natively in mdl. 
Here's my tabs implementation:

`<mdl-tabs mdl-ripple [mdl-tab-active-index]="activeIndex" (mdl-tab-active-changed)="tabChanged($event)">
    <mdl-tab-panel *ngFor="let listing of listings">
      <mdl-tab-panel-title>
        <img [src]="listing.mapImage.url" alt="" height="27" width="27">
      </mdl-tab-panel-title>
    </mdl-tab-panel>
  </mdl-tabs>`

I'll try getting a fix but would really appreciate any insights as to go about it.
