### ISSUE TITLE
How to set up custom color themes in angular2-webpack-starter?

### ISSUE THREAD

**Issue by mmgdort** [mseemann/angular2-mdl#60]
angular2-webpack-starter: https://github.com/AngularClass/angular2-webpack-starter

The library itself works, importing the module. 

But I was wondering how to get this part working

```` sass
@import "color-definitions";

$color-primary: $palette-blue-500;
$color-primary-dark: $palette-blue-700;
$color-accent: $palette-amber-A200;
$color-primary-contrast: $color-dark-contrast;
$color-accent-contrast: $color-dark-contrast;

@import 'material-design-lite';
```
The @import 'material-design-lite' sentence fails.

The sass files are working on angular2-webpack-starter  (https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-include-SCSS-in-components)

Amazing project, by the way,
Congratulations

**Comment by mseemann** [comment]
Hi, I don't know exactly how to setup the scss files for webpack. The example above works because I have added the sources as additional import paths for the scss compiler: ${__dirname}/node_modules/angular2-mdl/src/scss-mdl. If you don't find a way in your case you can use the path directly (e.g. @import "../node_modules/angular2-mdl/src/scss-mdl/color-definitions" depending on your configuration)

Nevertheless I would suggest asking your question at stack overflow to get feedback from a bigger community (there is also a tag for angular2-mdl: http://stackoverflow.com/questions/tagged/angular2-mdl)
