### ISSUE TITLE
mdl-textfield not showing error required in Reactive Form

### ISSUE THREAD

**Issue by AClavijo** [mseemann/angular2-mdl#622]
Hi,

I put a mdl-textfield, where it is required in a reactive form like this:

template:
`<mdl-textfield type="text" name="firstname" label="Prénom" floating-label class="mdl-textfield--full-size" formControlName="firstname" error-msg="firstname is required"></mdl-textfield>`

component:
firstname: this.fb.control('', Validators.required);

The error is not display when the component is load, ok normal. But when i enter text and then remove it, nothing appear. I've tried some tricky things like:

`<mdl-textfield type="text" name="firstname" label="Prénom" floating-label class="mdl-textfield--full-size" formControlName="firstname" error-msg="firstname is required" [class.is-invalid]="firstnameCtrl.invalid"></mdl-textfield>`

or

`<mdl-textfield type="text" name="firstname" label="Prénom" floating-label class="mdl-textfield--full-size" formControlName="firstname" error-msg="firstname is required" [class.is-invalid]="firstnameCtrl.hasError('required')"></mdl-textfield>`

In this case, the error message appear, but just a millisecond and is automaticaly hidden although the expression is still valid

In fact i'm still searching to how display error message with reactive form. Can you help me?
Thank's

**Comment by mseemann** [comment]
hi. please create a plnkr that demonstrates your problem. thx.

**Comment by AClavijo** [comment]
hi,

[here the plnkr of my problem](http://plnkr.co/edit/fPjobI373OaU5bYX7Hqd?p=preview)

**Comment by mseemann** [comment]
The problem is the mdl-controls are usually designed to work with the browsers native validity checking. Your second approach is right. But you need to disable the native Browser checks. This can be done by the directive disableNativeValidityChecking (you can configre this behavior globally see: https://github.com/mseemann/angular2-mdl/wiki/Mdl-Textfield-and-native-validity-checking ). To be complete you have to write:

`disableNativeValidityChecking  [class.is-invalid]="usernameCtrl.invalid && usernameCtrl.dirty"`

I put this on the List for version 3 - may be i find a solution that is less verbose and works out of the box.
