### ISSUE TITLE
ReactiveForm validation not showing error

### ISSUE THREAD

**Issue by leolorenzoluis** [mseemann/angular2-mdl#709]
In your example for ReactiveForms, you have last name `FormControl` with required validator. However, the demo app doesn't show the message when last name is required.

**Comment by mseemann** [comment]
the error styles are only applied to mdl-textfield if the validity property of the input element is not valid. a reactive form did not change this property because the state is completely handled by angular. if you need error styling for your mdl-textfield (with reactive form binding) you need to set the appropriate styles for the css class ng-dirty, ng-touched and so on. usually this only changes the color for input and label and sets the error message to visible. also this approach gibes you teh flexibility when to set the error styling: always, only if the input field is touched, ...
